name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - staging1
          - staging4

permissions: write-all

jobs:
  update_badges:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Release version
      run: echo ${{ github.ref_name }}
    - name: Target stage
      run: echo ${{ github.event.inputs.environment }}
    - name: Update badges
      run: |
        echo "Renaming badges with -r(release) ${{ github.ref_name }} -s(stage) ${{ github.event.inputs.environment }}"
        .github/update-badges.sh -r ${{ github.ref_name }} -s ${{ github.event.inputs.environment }}  
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "🤖 - update badges"
        push_options: --force
        branch: main

