# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - staging1
          - staging4

permissions: write-all

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # by default, it uses a depth of 1
        # this fetches all history so that we can read each commit
        fetch-depth: 0
        ref: ${{ github.head_ref }}
        
    - name: Release version
      run: echo ${{ github.ref_name }}
    - name: Target stage
      run: echo ${{ github.event.inputs.environment }}
    - name: Update badges
      run: |
        echo "Renaming badges with -r(release) ${{ github.ref_name }} -s(stage) ${{ github.event.inputs.environment }}"
        .github/update-badges.sh -r ${{ github.ref_name }} -s ${{ github.event.inputs.environment }}  
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update badges"
        push_options: --force

